### ISSUE TITLE
Error decoding iec61850 GOOSE

### ISSUE THREAD

**Issue by tfm1988** [pyasn1/pyasn1#65]
Thanks for this great library !

In my project I am trying to perform an IEC61850 GOOSE packet parser. Unfortunately I came across this package that has the "structure" type in its dataset. For this case, pyasn1 fails to decode the packet. Could anyone help me with this issue?

It should be noted that Wireshark does not complain about reading the packet.

The code is:
```
###############################
# Import SCAPY and ASN1 modules
###############################

from pyasn1.codec.ber import decoder
from pyasn1.type import univ, tag
from scapy.all import rdpcap
from scapy.layers.l2 import Ether
from scapy.layers.l2 import Dot1Q

###############################
# Import Goose module
###############################
from goose.goose_pdu import IECGoosePDU
from goose.goose import GOOSE
from goose.goose import GOOSEPDU

###############################
# Constants
###############################
DEBUG = 3 # Debugging on
GOOSE_TYPE = 0x88b8

###############################
# Functions
###############################

def gooseTest(pkt):
    isGoose = False
    # Test for a Goose Ether Type
    if pkt.haslayer('Dot1Q'):
        if pkt['Dot1Q'].type == GOOSE_TYPE: isGoose = True
    if pkt.haslayer('Ether'):
        if pkt['Ether'].type == GOOSE_TYPE: isGoose = True
    return isGoose

# Função chamada quando um pacote é recebido
def packet_callback(packet):
    global GsData # Informa ao interpretador que se deve usar a variavel global GsData definida em main e não criar uma local
    global df     # Informa ao interpretador que se deve usar a variavel global df definida em main e não criar uma local
    if gooseTest(packet):
                        
        # Use pyasn1 to parse the Goose header and the Goose PDU header
        d = GOOSE(packet.load)

        # Grab the Goose PDU for processing
        encoded_data = d[GOOSEPDU].original
                
        if DEBUG > 2: 
            from pyasn1 import debug
            debug.setLogger(debug.Debug('all'))

        g = IECGoosePDU().subtype(
            implicitTag=tag.Tag(
                tag.tagClassApplication,
                tag.tagFormatConstructed,
                1
            )
        )
        decoder.decode.defaultErrorState = decoder.stDumpRawValue
        decoded_data, unprocessed_trail = decoder.decode(
            encoded_data,
            asn1Spec=g
        )
                        
        print('decoded_data===>',decoded_data)
        print('\n\n')
        print('unprocessed_trail===>',unprocessed_trail)
        print('\n\n')
        
if __name__ == "__main__":

    # Lendo pcap
    pcap_file = "PCAPs/pacoteSacana.pcapng"
    packets = rdpcap(pcap_file)
    # Parser
    for packet in packets:
        packet_callback(packet)

```
The error is

```
2024-05-09 10:27:47,585 pyasn1: decoder left scope IECGoosePDU.AllData, call completed
2024-05-09 10:27:47,585 pyasn1: decoder called at scope IECGoosePDU.AllData with state 0, working with up to None octets of substrate: <_io.BytesIO object at 0x0000021C7D4A7F10>
2024-05-09 10:27:47,586 pyasn1: tag decoded into <TagSet object, tags 128:32:2>, decoding length
2024-05-09 10:27:47,586 pyasn1: value length decoded into 7
2024-05-09 10:27:47,586 pyasn1: candidate ASN.1 spec is Data
2024-05-09 10:27:47,586 pyasn1: value decoder chosen for an ambiguous type by type ID 14
2024-05-09 10:27:47,586 pyasn1: codec ChoicePayloadDecoder chosen by ASN.1 spec, decoding value
2024-05-09 10:27:47,586 pyasn1: decoding <TagSet object, tags 128:32:2> as untagged CHOICE
2024-05-09 10:27:47,586 pyasn1: decoder called at scope IECGoosePDU.AllData.Data with state 2, working with up to 7 octets of substrate: <_io.BytesIO object at 0x0000021C7D4A7F10>
2024-05-09 10:27:47,586 pyasn1: candidate ASN.1 spec is a map of:
2024-05-09 10:27:47,586 pyasn1:   <TagSet object, tags 128:32:1> -> SequenceOf
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:32:2> -> SequenceOf
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:0:3> -> Boolean
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:0:4> -> BitString
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:0:5> -> Integer
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:0:6> -> Integer
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:0:7> -> FloatingPoint
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:0:8> -> Real
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:0:9> -> OctetString
2024-05-09 10:27:47,587 pyasn1:   <TagSet object, tags 128:0:10> -> VisibleString
2024-05-09 10:27:47,588 pyasn1:   <TagSet object, tags 128:0:12> -> TimeOfDay
2024-05-09 10:27:47,588 pyasn1:   <TagSet object, tags 128:0:13> -> Integer
2024-05-09 10:27:47,588 pyasn1:   <TagSet object, tags 128:0:14> -> BitString
2024-05-09 10:27:47,588 pyasn1:   <TagSet object, tags 128:0:15> -> ObjectIdentifier
2024-05-09 10:27:47,588 pyasn1:   <TagSet object, tags 128:0:16> -> MMSString
2024-05-09 10:27:47,588 pyasn1:   <TagSet object, tags 128:0:17> -> UtcTime
Traceback (most recent call last):
  File "\Debug_gsmonitor_v2.py", line 80, in <module>
    packet_callback(packet)
  File "\Debug_gsmonitor_v2.py", line 63, in packet_callback
    decoded_data, unprocessed_trail = decoder.decode(
                                      ^^^^^^^^^^^^^^^
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 2114, in __call__
    for asn1Object in streamingDecoder:
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 1983, in __iter__
    for asn1Object in self._singleItemDecoder(
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 1839, in __call__
    for value in concreteDecoder.valueDecoder(
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 774, in valueDecoder
[goose.zip](https://github.com/pyasn1/pyasn1/files/15263249/goose.zip)

    for component in decodeFun(substrate, componentType, **options):
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 1839, in __call__
    for value in concreteDecoder.valueDecoder(
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 894, in valueDecoder
    for component in decodeFun(substrate, componentType, **options):
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 1839, in __call__
    for value in concreteDecoder.valueDecoder(
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 1203, in valueDecoder
    for component in decodeFun(
  File "\local-packages\Python312\site-packages\pyasn1\codec\ber\decoder.py", line 1771, in __call__
    LOG('new candidate ASN.1 spec is %s, chosen by %s' % (chosenSpec is None and '<none>' or chosenSpec.prettyPrintType(), tagSet))
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\local-packages\Python312\site-packages\pyasn1\type\univ.py", line 2114, in prettyPrintType
    representation += self.componentType.prettyPrintType(scope)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\local-packages\Python312\site-packages\pyasn1\type\univ.py", line 2850, in prettyPrintType
    for idx, componentType in enumerate(self.componentType.values() or self._componentValues):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\local-packages\Python312\site-packages\pyasn1\type\base.py", line 213, in plug
    raise error.PyAsn1Error('Attempted "%s" operation on ASN.1 schema object' % name)
pyasn1.error.PyAsn1Error: Attempted "__iter__" operation on ASN.1 schema object
```
My Python version is 3.12.3 and pip freeze is:
      
```
pyasn1==0.6.0
scapy==2.5.0
```

[projeto.zip](https://github.com/pyasn1/pyasn1/files/15263416/projeto.zip)

**Comment by user3472g** [comment]
Did you ever find a solution to this? I have a simliar problem with recursive structures.
